name: Build and Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Compress build folder
        run: tar -czf build.tar.gz build

      - name: Deploy to EC2
        env:
          AWS_EC2_IP: ${{ secrets.AWS_EC2_IP }}
          EC2_USER: ${{ secrets.EC2_USER }}
          DESTINATION_PATH: ${{ secrets.DESTINATION_PATH }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

          # Copy build archive to EC2
          scp -i ssh_key -o StrictHostKeyChecking=no build.tar.gz ${{ env.EC2_USER }}@${{ env.AWS_EC2_IP }}:${{ env.DESTINATION_PATH }}

          # Connect to EC2 and deploy
          ssh -i ssh_key -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.AWS_EC2_IP }} << 'EOF'
            cd ${{ env.DESTINATION_PATH }}
            tar -xzf build.tar.gz
            rm build.tar.gz
            # Optional: Restart services if needed, e.g., pm2, nginx, apache
            echo "Deployment complete!"
          EOF
